---

- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create VM	
    azure_rm_virtualmachine:
     resource_group: myResourceGroup
     name: mywindows2008
     storage_account: myvm23715
     vm_size: Standard_DS1_v2
     public_ip_allocation_method: Dynamic
     admin_username: pawan
     admin_password: Pawan123
     open_ports:
      - 3389
      - 5986
     os_type: Windows
     image:
      publisher: MicrosoftWindowsServer
      offer: WindowsServer
      sku: 2008-R2-SP1
      version: latest
