---
- name: Install all packages
  hosts: node2
  become: true
  tasks:
   - name: Installing tomcat 
     yum: name={{item}} state=present update_cache=yes
     with_items:
       - java-1.8.0-openjdk.x86_64
       - firewalld
       - wget
       - httpd
